[workspace]
members = [
    "crates/shared",
    "crates/client",
    "crates/server",
    "crates/game",
    "crates/networking",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
bevy = "0.17.3"
bevy_ecs = "0.17.3"
bevy_egui = "0.38"
bevy-inspector-egui = "0.35"
bevy_replicon = "0.36"
bevy_replicon_renet = "0.12"
bevy_renet = "3.0.0"
bevy_rapier3d = { version = "0.32.0", features = ["enhanced-determinism"] }
glam = "0.30.9"

bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

