[package]
name = "networking"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_renet = { workspace = true }
bincode = { workspace = true }
shared = { path = "../shared" }
server = { path = "../server" }

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3